### PR TITLE
Adding a failing test to the rebalancer.

### PR DESCRIPTION
**Pull request by SpiegelSoft**
I don't know what the fix is yet: I was testing in the B-tree counting branch and this fell over.

### CODE REVIEW

**Comment by ayende** [comment]
The problem appears to be with merging of branch pages.
We aren't doing it properly, the code right now always assume we are
merging leaf pages.

**Comment by SpiegelSoft** [comment]
OK, thanks for that.  I'll look at it tonight if I get a chance, and if someone doesn't beat me to it.

**Comment by ayende** [comment]
Oh, I am fixing this now

**Comment by ayende** [comment]
Correction, I don't have enough time to do it today. If you can give it
some time, that would be great.
I am continuing the discussion in the mailing list.

**Comment by SpiegelSoft** [comment]
No problems -- I'll be interested to read the fix.

On 21 August 2013 12:31, Ayende Rahien notifications@github.com wrote:

> Oh, I am fixing this now
> 
> On Wed, Aug 21, 2013 at 2:23 PM, Rob Lyndon notifications@github.comwrote:
> 
> > OK, thanks for that. I'll look at it tonight if I get a chance, and if
> > someone doesn't beat me to it.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ayende/raven.voron/pull/3#issuecomment-23010393>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ayende/raven.voron/pull/3#issuecomment-23010706
> .

## 

_Rob Lyndon_
9258-8945-2998
Spotlight http://www.spotlight.com/9258-8945-2998
www.thetamingoftheshrew.co.uk
*
*

**Comment by ayende** [comment]
https://groups.google.com/forum/#!topic/raven-voron/52t0cSXIGfQ

**Pull request merged**
