### PR TITLE
FoundationDB performance comparison for Voron

### PR DESCRIPTION
**Pull request by jahmai-ca**
Using FoundationDB C# Client from here : https://github.com/Doxense/foundationdb-dotnet-client
(This is included in the PR).

It will compile as-is, but to run it you must;
1. Install FoundationDB for windows from https://foundationdb.com/get
2. Copy the contents of C:\ProgramData\foundationdb\fdb.cluster into the same file in the project folder (this is like a connection string file)

I couldn't perform a comparison myself as Voron kept crashing with AccessViolationException on my machine...

### CODE REVIEW

**Comment by KrzysFR** [comment]
Hi there, I'm the author of the FoundationDB .NET binding. Glad to see it used here :) 

First, I should point out that this is not an official binding from the FDB folks, and that I'm wrapping their official C API from managed code.

Looking at the test code, I see that the parallel read and parallel write methods are not really using the most efficient way to do this kind of operations with FoundationDB. Doing a single read per transaction is basically the worst case scenario for FoundationDB where you will pay the full overhead per read.

The most efficient way to read multiple random keys is to issue concurrent reads PER transaction. I've added a GetValuesAsync(IEnumerable<...>) method to the API just to deal with this scenario. The best case would be to read a few hundred keys per transaction.

Also, the code is mixing up Tuple encoding and binary encoding. Calling Pack() on a slice (which is already a binary key) will escape the key twice. So if you really just want to use integers as keys, you can just call db.Pack(id). Or if you have a sequence of ids, you can pack them all at once using the FdbTupe.PackRange<T>(IEnumerable<T>) helper.

A better way to write the read parallel test code would be something like this:

``` CSharp
        private static async Task ReadInternalAsync(IEnumerable<int> ids, PerfTracker perfTracker, FdbDatabase db)
        {
            Stopwatch sw = Stopwatch.StartNew();
            using (var tx = db.BeginTransaction())
            {
                await tx.GetValuesAsync(db.GlobalSpace.PackRange(ids));
            }
            perfTracker.Record(sw.ElapsedMilliseconds);
        }
```

The number of ids per list should ideally be a few hundreds max (there is time limit per transaction).

**Comment by ayende** [comment]
Hm,
Since I am not an expert (or in any way familiar) with FoundationDB, could
you do a pull request that would do an optimal access pattern?

_Oren Eini_
CEO
Hibernating Rhinos
Cellular: +972-52-548-6969
Office:    +972-4-674-7811
Fax:       +972-153-4622-7811

**Comment by KrzysFR** [comment]
Sure, I'll try to work on that tomorrow and see if I can build an run your performance test suite.

**Comment by ayende** [comment]
Thanks.

_Oren Eini_
CEO
Hibernating Rhinos
Cellular: +972-52-548-6969
Office:    +972-4-674-7811
Fax:       +972-153-4622-7811

**Pull request merged**
